import Head from 'next/head'
import { Inter } from 'next/font/google'
import HeaderComponent from '@/components/header'
import SwapComponent from '@/components/swap'
import { useAccount, useConnect } from 'wagmi'
import { InjectedConnector } from 'wagmi/connectors/injected'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { address, isConnected } = useAccount();
  const { connect } = useConnect({
    connector: new InjectedConnector(),
  });
  
  return (
    <>
      <Head>
        <title>DCX SWAP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-5">
          <HeaderComponent connect={connect} isConnected={isConnected} address={address}></HeaderComponent>
          <SwapComponent connect={connect} isConnected={isConnected} address={address}></SwapComponent>
      </main>
    </>
  )
}
